"""Initial Migration

Revision ID: b2265ea4159a
Revises: 52438c2a49cc
Create Date: 2018-10-22 18:13:35.966694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2265ea4159a'
down_revision = '52438c2a49cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.String(), nullable=True))
    op.drop_column('blogs', 'blog_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###
